### ISSUE TITLE
Add the package to the npm registry (www.npmjs.com) when 0.1.0 is released

### ISSUE THREAD

**Issue by omasanori** [jgm/djot.js#20]
I guess anyone won't forget that but just in case...

**Comment by jgm** [comment]
I think I managed to do this correctly.
0.1.0 failed because the name `djot` was rejected (too close to `dot`).
So I went for `djot-js`.

**Comment by omasanori** [comment]
Thanks!

**Comment by jgm** [comment]
Actually having second thoughts about the name, and wanted to raise it here because I believe I can still "unpublish" within 24 hours.  @matklad would be good to have your feedback too.  `djot-js` is a bit weird because, after all, this is a repository of JavaScript packages, so of course it's `js`.  (But then, it's really `ts`.)  `djot-markup` seems potentially better, though of course there's a question whether it's really mark*up*. Any thoughts?

**Comment by matklad** [comment]
Yeah, dj-js is suboptimal for npm. But nothing obviously better comes to mind. djotlang?

**Comment by jgm** [comment]
djotlang sounds like it should be a programming language.
djot-markup is the best alternative I've thought of, don't know if it's good enough to change though.  Advantage is that you can see what kind of thing it is from the name.

**Comment by omasanori** [comment]
`@djot/djot`? (for flexibility in the future, like splitting the package into `@djot/parser` and `@djot/html-render` and making `@djot/djot` a meta-package for instance)

**Comment by omasanori** [comment]
(if you can create the `djot` organization on npmjs.com; which might be rejected like the `djot` package)

**Comment by omasanori** [comment]
Usually scoped packages are named as `@foo/core`, `@foo/cli` (for CLI entrypoint), `@foo/node` (for Node.js support / shim), etc. I think `@foo/foo` is fine, however.

**Comment by bpj** [comment]
Is there *any* published version ATM? I get no matches found for all the above mentioned.

**Comment by jgm** [comment]
No, I unpublished and have not yet published under new name, because I'm still not quite sure what name to use, but it will probably be @djot/djot.
